import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const sourcePath = path.join(root, "public", "muralizer.html");
const outputPath = path.join(root, "public", "index.html");

async function main() {
  try {
    const sourceHtml = await fs.readFile(sourcePath, "utf8");
    const banner = "<!-- Auto-generated by scripts/build-web.mjs. Edit public/muralizer.html instead. -->\n";
    await fs.writeFile(outputPath, `${banner}${sourceHtml}`, "utf8");

    const stat = await fs.stat(outputPath);
    console.log(`Built ${path.relative(root, outputPath)} (${stat.size} bytes)`);
  } catch (err) {
    console.error("build:web failed:", err && err.message ? err.message : err);
    process.exitCode = 1;
  }
}

main();
